Update check_app.yaml

diff --git a/.github/workflows/check_app.yaml b/.github/workflows/check_app.yaml
--- a/.github/workflows/check_app.yaml
+++ b/.github/workflows/check_app.yaml
@@ -44,6 +44,12 @@ jobs:
 
       - name: Make install.sh executable
         run: chmod +x install.sh
+          if [ ! -f "install.sh" ]; then
+            echo "❌ File install.sh not found!"
+            ls -la
+            exit 1
+          fi
+          chmod +x install.sh
 
       - name: Run install.sh (emulated)
         env:
